#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : diskcache
Version  : 5.2.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/49/07/079b8b4eb2aba194fca4562c7f014ea45a40130ebff539628c05c52d9050/diskcache-5.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/49/07/079b8b4eb2aba194fca4562c7f014ea45a40130ebff539628c05c52d9050/diskcache-5.2.1.tar.gz
Summary  : Disk Cache -- Disk and file backed persistent cache.
Group    : Development/Tools
License  : Apache-2.0
Requires: diskcache-license = %{version}-%{release}
Requires: diskcache-python = %{version}-%{release}
Requires: diskcache-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : tox
BuildRequires : tox-python

%description
============================
        
        `DiskCache`_ is an Apache2 licensed disk and file backed cache library, written
        in pure-Python, and compatible with Django.
        
        The cloud-based computing of 2021 puts a premium on memory. Gigabytes of empty
        space is left on disks as processes vie for memory. Among these processes is
        Memcached (and sometimes Redis) which is used as a cache. Wouldn't it be nice
        to leverage empty disk space for caching?
        
        Django is Python's most popular web framework and ships with several caching
        backends. Unfortunately the file-based cache in Django is essentially
        broken. The culling method is random and large caches repeatedly scan a cache
        directory which slows linearly with growth. Can you really allow it to take
        sixty milliseconds to store a key in a cache with a thousand items?
        
        In Python, we can do better. And we can do it in pure-Python!

%package license
Summary: license components for the diskcache package.
Group: Default

%description license
license components for the diskcache package.


%package python
Summary: python components for the diskcache package.
Group: Default
Requires: diskcache-python3 = %{version}-%{release}

%description python
python components for the diskcache package.


%package python3
Summary: python3 components for the diskcache package.
Group: Default
Requires: python3-core
Provides: pypi(diskcache)

%description python3
python3 components for the diskcache package.


%prep
%setup -q -n diskcache-5.2.1
cd %{_builddir}/diskcache-5.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1619707430
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/diskcache
cp %{_builddir}/diskcache-5.2.1/LICENSE %{buildroot}/usr/share/package-licenses/diskcache/a78e926f2f97675e16a3dbdb7a61793d3f675ab8
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/diskcache/a78e926f2f97675e16a3dbdb7a61793d3f675ab8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
